In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
data = pd.read_csv("/datasets/Prepro_Kidney.csv")
data.head()

id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd  
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd  
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd  

[5 rows x 26 columns]

In [3]:
data.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [4]:
data['classification'].value_counts()

ckd       248
notckd    150
ckd\t       2
Name: classification, dtype: int64

In [5]:
data['classification']=data['classification'].replace('ckd\t','ckd')
data['classification'].value_counts()

ckd       250
notckd    150
Name: classification, dtype: int64

In [7]:
data = data.drop("id", axis = 1)

KeyError: "['id'] not found in axis"

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             391 non-null    float64
 1   bp              388 non-null    float64
 2   sg              353 non-null    float64
 3   al              354 non-null    float64
 4   su              351 non-null    float64
 5   rbc             248 non-null    object 
 6   pc              335 non-null    object 
 7   pcc             396 non-null    object 
 8   ba              396 non-null    object 
 9   bgr             356 non-null    float64
 10  bu              381 non-null    float64
 11  sc              383 non-null    float64
 12  sod             313 non-null    float64
 13  pot             312 non-null    float64
 14  hemo            348 non-null    float64
 15  pcv             330 non-null    object 
 16  wc              295 non-null    object 
 17  rc              270 non-null    obj

In [9]:
data=data.drop_duplicates()

In [10]:
from sklearn.preprocessing import LabelEncoder

for i in data.columns:
    if data[i].dtype=='object':
        data[i]=LabelEncoder().fit_transform(data[i])
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             391 non-null    float64
 1   bp              388 non-null    float64
 2   sg              353 non-null    float64
 3   al              354 non-null    float64
 4   su              351 non-null    float64
 5   rbc             400 non-null    int64  
 6   pc              400 non-null    int64  
 7   pcc             400 non-null    int64  
 8   ba              400 non-null    int64  
 9   bgr             356 non-null    float64
 10  bu              381 non-null    float64
 11  sc              383 non-null    float64
 12  sod             313 non-null    float64
 13  pot             312 non-null    float64
 14  hemo            348 non-null    float64
 15  pcv             400 non-null    int64  
 16  wc              400 non-null    int64  
 17  rc              400 non-null    int

In [11]:
from sklearn.impute import KNNImputer

imp = KNNImputer(n_neighbors = 5)
data_p = imp.fit_transform(data)
data_p = pd.DataFrame(data_p, columns = data.columns)
data_p.isnull().sum()

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [12]:
mnop = data.to_csv("Preprocessed_dataset.csv")

In [16]:
y = np.array(data_p['classification'])
y = y.reshape(-1, 1)
X = np.array(data_p.drop(['classification'], axis = 1))

In [17]:
print(X)
print(y)

[[48.    80.     1.02  ...  0.     0.     0.   ]
 [ 7.    50.     1.02  ...  0.     0.     0.   ]
 [62.    80.     1.01  ...  1.     0.     1.   ]
 ...
 [12.    80.     1.02  ...  0.     0.     0.   ]
 [17.    60.     1.025 ...  0.     0.     0.   ]
 [58.    80.     1.025 ...  0.     0.     0.   ]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [18]:
print("Before oversampling, counts of label '0': {}".format(sum(y == 0)))
print("Before oversampling, counts of label '1': {}".format(sum(y == 1)))

Before oversampling, counts of label '0': [250]
Before oversampling, counts of label '1': [150]


In [19]:
# SPLITTING DATA INTO TRAIN AND TEST DATASETS
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [22]:
!pip install lazypredict

In [23]:
from lazypredict.Supervised import LazyClassifier

clf = LazyClassifier(verbose = 0, ignore_warnings = True, custom_metric = None)

models, predictions = clf.fit(X_train, X_test, y_train, y_test)
models

100%|██████████| 29/29 [00:00<00:00, 34.47it/s]

[LightGBM] [Info] Number of positive: 112, number of negative: 188
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000140 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 602
[LightGBM] [Info] Number of data points in the train set: 300, number of used features: 24
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.373333 -> initscore=-0.517943
[LightGBM] [Info] Start training from score -0.517943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best

Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model                                                                           
NuSVC                              0.99               0.99     0.99      0.99   
SVC                                0.99               0.99     0.99      0.99   
ExtraTreesClassifier               0.99               0.99     0.99      0.99   
LogisticRegression                 0.99               0.99     0.99      0.99   
BernoulliNB                        0.98               0.98     0.98      0.98   
RidgeClassifierCV                  0.97               0.98     0.98      0.97   
RidgeClassifier                    0.97               0.98     0.98      0.97   
LinearDiscriminantAnalysis         0.97               0.98     0.98      0.97   
DecisionTreeClassifier             0.98               0.97     0.97      0.98   
SGDClassifier                      0.98               0.97     0.97      0.98   
BaggingClassifier                  0.98               0.97     0.97      0.98   
LabelPropagation                   0.97               0.97     0.97      0.97   
CalibratedClassifierCV             0.97               0.97     0.97      0.97   
KNeighborsClassifier               0.97               0.97     0.97      0.97   
LabelSpreading                     0.97               0.97     0.97      0.97   
PassiveAggressiveClassifier        0.96               0.96     0.96      0.96   
LinearSVC                          0.96               0.96     0.96      0.96   
RandomForestClassifier             0.97               0.96     0.96      0.97   
Perceptron                         0.95               0.95     0.95      0.95   
NearestCentroid                    0.94               0.95     0.95      0.94   
XGBClassifier                      0.94               0.93     0.93      0.94   
AdaBoostClassifier                 0.94               0.92     0.92      0.94   
ExtraTreeClassifier                0.87               0.83     0.83      0.86   
LGBMClassifier                     0.85               0.80     0.80      0.84   
QuadraticDiscriminantAnalysis      0.62               0.50     0.50      0.47   
GaussianNB                         0.62               0.50     0.50      0.47   
DummyClassifier                    0.62               0.50     0.50      0.47   

                               Time Taken  
Model                                      
NuSVC                                0.02  
SVC                                  0.01  
ExtraTreesClassifier                 0.09  
LogisticRegression                   0.02  
BernoulliNB                          0.02  
RidgeClassifierCV                    0.01  
RidgeClassifier                      0.02  
LinearDiscriminantAnalysis           0.03  
DecisionTreeClassifier               0.01  
SGDClassifier                        0.01  
BaggingClassifier                    0.03  
LabelPropagation                     0.02  
CalibratedClassifierCV               0.03  
KNeighborsClassifier                 0.02  
LabelSpreading                       0.02  
PassiveAggressiveClassifier          0.01  
LinearSVC                            0.01  
RandomForestClassifier               0.13  
Perceptron                           0.01  
NearestCentroid                      0.01  
XGBClassifier                        0.05  
AdaBoostClassifier                   0.09  
ExtraTreeClassifier                  0.01  
LGBMClassifier                       0.11  
QuadraticDiscriminantAnalysis        0.03  
GaussianNB                           0.01  
DummyClassifier                      0.01

In [25]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, y_pred))
print()
print(confusion_matrix(y_test, y_pred))
print()
print(classification_report(y_test, y_pred))

0.99

[[62  0]
 [ 1 37]]

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99        62
         1.0       1.00      0.97      0.99        38

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100



In [29]:
y_pred = log_reg.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]]


In [30]:
import joblib

joblib.dump(value = [data_p, scaler, log_reg], filename = "/models/kidney_models.pkl")

['/content/kidney_models.pkl']

In [31]:
abc = data_p.to_csv("Preprocessed_dataset.csv")